js integration test orbs + other orbs cleanup
ricardo-ch/ricardo-orbs pull request #78
Opened 2023-03-20 15:18 UTC by magrytos

Refactor, cleanup and new orbs for FE. This PR covers all use cases for FE pipelines, meaning every FE config can be composed only with orbs. This will be a major release.
- testing jobs using parallelism for `cypress` and `eslint`, refactoring `jest` job
- all logic related to `tmp-test-list` file was moved into orbs to simplify ci related scripts in `package.json`
- force scripts to be named `ci:*`:
  - `ci:build`
  - `ci:build-storybook`
  - `ci:cypress:beta`
  - `ci:cypress`
  - `ci:lint`

Some proofs that it works:
[listing-form](https://app.circleci.com/pipelines/github/ricardo-ch/listing-form-spa?branch=orbs-only)
[marketplace-frontend-app](https://app.circleci.com/pipelines/github/ricardo-ch/marketplace-frontend-app?branch=ci-improvements)

2023-03-23 09:26 UTC, magrytos commented on src/commands/js_docker_prebuild_steps.yml
.env.sentry is not used anymore

2023-03-23 09:27 UTC, magrytos commented on src/jobs/js_jest_test_runner_job.yml
This file was modified and renamed to js_jest_runner_job.yml

2023-03-23 09:29 UTC, magrytos commented on src/jobs/js_yarn_runner_job.yml
only file structure changes here

2023-03-24 06:14 UTC, mbriziarelli requested changes
LGTM. except the remaining js_jest_runner_job.yml

2023-03-24 08:42 UTC, mbriziarelli approved these changes

2023-03-24 13:15 UTC, mbriziarelli approved these changes

2023-03-24 13:19 UTC, merged